# Generated by Django 5.1.4 on 2025-01-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Venue Name")),
                (
                    "address",
                    models.CharField(max_length=50, verbose_name="Venue Address"),
                ),
                ("zip_code", models.IntegerField(verbose_name="Zip Code")),
                ("phone", models.IntegerField(verbose_name="Phone Number")),
                ("web", models.URLField(verbose_name="Website")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                ("capacity", models.IntegerField(verbose_name="Capacity")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Event Name")),
                ("event_date", models.DateField(verbose_name="Event Date")),
                (
                    "manager",
                    models.CharField(max_length=50, verbose_name="Event Manager"),
                ),
                ("description", models.TextField(verbose_name="Event Description")),
                (
                    "attendees",
                    models.ManyToManyField(blank=True, to="events.eventuser"),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.venue",
                    ),
                ),
            ],
        ),
    ]
