# Generated by Django 5.1.4 on 2025-01-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("List", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="status",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
